# Generated by Django 2.2.6 on 2019-12-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VDJ_Anchors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchor',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='anchor',
            name='document',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
