# Generated by Django 2.2.7 on 2019-11-23 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VDJ_Anchors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anchor',
            new_name='VGene',
        ),
    ]
